name: BehaviorCloningProject
dependencies:
- pip >= 9
- jupyter
- matplotlib
- numpy
- scipy
- scikit-learn
- pandas
- pillow
- keras
- menpo::opencv3
- pip:
  - tensorflow >= 0.12.0rc1
  - python-socketio
  - eventlet
  - flask
  - tqdm
  - more-itertools
